#!/usr/bin/env php
<?php

// application.php

require __DIR__.'/vendor/autoload.php';

use Maid\Command\Pull;
use Symfony\Component\Console\Application;

$application = new Application('Maid', '@package_version@');

// ... register commands
$application->add(new Pull());

$application->run();
