#!/usr/bin/env php
<?php

// application.php

require __DIR__.'/vendor/autoload.php';

use Maid\Command\Pull;
use Maid\Command\Store;
use Maid\Command\Module;
use Symfony\Component\Console\Application;

$application = new Application('Maid', '@package_version@');

// ... register commands
$application->add(new Pull());
$application->add(new Store());
$application->add(new Module());

$application->run();
